import type { UserEntity } from '@model/user.entity';
import { GENDER } from '@model/user.entity';

export const UserSeed: Partial<UserEntity>[] = [
  {
    name: 'Gunawan Prasetya',
    email: 'gunawan.pras776@gmail.com',
    username: 'gunawan.pras',
    password: 'gunawan123@!',
    birth_date: new Date('1992-08-23'),
    gender: GENDER.Male,
    address: 'Jl. Cililitan no24, Cililitan, Jakarta Timur, DKI Jakarta',
    city: 'Jakarta Timur',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '082135230995',
  },
  {
    name: 'Dewi Santoso',
    email: 'dewi.santoso999@gmail.com',
    username: 'dewi.sant',
    password: 'dewi2024@!',
    birth_date: new Date('1991-02-12'),
    gender: GENDER.Female,
    address: 'Jl. Mangga Dua no8, Mangga Dua, Jakarta Pusat, DKI Jakarta',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '081238764321',
  },
  {
    name: 'Ahmad Ramadhan',
    email: 'ahmad.ramadhan53@gmail.com',
    username: 'ahmad.ram',
    password: 'ramadhan2024@!',
    birth_date: new Date('2001-01-20'),
    gender: GENDER.Male,
    address: 'Jl. Buncit Raya no20, Mampang, Jakarta Selatan, DKI Jakarta',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '085673456789',
  },
  {
    name: 'Siti Nurhaliza',
    email: 'siti.nurhaliza77@gmail.com',
    username: 'siti.nur',
    password: 'nurhaliza2024@!',
    birth_date: new Date('1999-03-18'),
    gender: GENDER.Female,
    address: 'Jl. Tebet Raya no13, Tebet, Jakarta Selatan, DKI Jakarta',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '082137654321',
  },
  {
    name: 'Budi Setiawan',
    email: 'budi.setiawan82@gmail.com',
    username: 'budi.set',
    password: 'budi2024@!',
    birth_date: new Date('1989-12-12'),
    gender: GENDER.Male,
    address: 'Jl. Sudirman no45, Kebayoran Baru, Jakarta Selatan, DKI Jakarta',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '085612345678',
  },
  {
    name: 'Agus Wijaya',
    email: 'agus.wijaya22@gmail.com',
    username: 'agus.wij',
    password: 'agus2024@!',
    birth_date: new Date('1980-10-29'),
    gender: GENDER.Male,
    address: 'Jl. Kebon Jeruk no2, Kebon Jeruk, Jakarta Barat, DKI Jakarta',
    city: 'Jakarta Barat',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '081245678912',
  },
  {
    name: 'Rina Kusuma',
    email: 'rina.kusuma88@gmail.com',
    username: 'rina.kus',
    password: 'rina2024@!',
    birth_date: new Date('1995-03-21'),
    gender: GENDER.Female,
    address: 'Jl. Tanah Abang no19, Tanah Abang, Jakarta Pusat, DKI Jakarta',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '082167894512',
  },
  {
    name: 'Doni Kurniawan',
    email: 'doni.kurniawan34@gmail.com',
    username: 'doni.kur',
    password: 'doni2024@!',
    birth_date: new Date('1995-07-23'),
    gender: GENDER.Male,
    address: 'Jl. Senen Raya no8, Senen, Jakarta Pusat, DKI Jakarta',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '085678932145',
  },
  {
    name: 'Yuni Astuti',
    email: 'yuni.astuti77@gmail.com',
    username: 'yuni.ast',
    password: 'yuni2024@!',
    birth_date: new Date('2000-11-23'),
    gender: GENDER.Female,
    address: 'Jl. Pulo Gadung no12, Pulo Gadung, Jakarta Timur, DKI Jakarta',
    city: 'Jakarta Timur',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '082156789431',
  },
  {
    name: 'Joko Susilo',
    email: 'joko.susilo99@gmail.com',
    username: 'joko.sus',
    password: 'joko2024@!',
    birth_date: new Date('2003-05-03'),
    gender: GENDER.Male,
    address: 'Jl. Kalimalang no5, Kalimalang, Jakarta Timur, DKI Jakarta',
    city: 'Jakarta Timur',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '081234567891',
  },
  {
    name: 'Tuti Wulandari',
    email: 'tuti.wulandari66@gmail.com',
    username: 'tuti.wul',
    password: 'tuti2024@!',
    birth_date: new Date('1997-02-22'),
    gender: GENDER.Female,
    address: 'Jl. Cikini Raya no3, Cikini, Jakarta Pusat, DKI Jakarta',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '082145678932',
  },
  {
    name: 'Andi Pratama',
    email: 'andi.pratama55@gmail.com',
    username: 'andi.prat',
    password: 'andi2024@!',
    birth_date: new Date('1999-08-27'),
    gender: GENDER.Male,
    address: 'Jl. Salemba Raya no1, Salemba, Jakarta Pusat, DKI Jakarta',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '085678923145',
  },
  {
    name: 'Lina Hartati',
    email: 'lina.hartati89@gmail.com',
    username: 'lina.hart',
    password: 'lina2024@!',
    birth_date: new Date('1995-07-12'),
    gender: GENDER.Female,
    address: 'Jl. Sudirman no55, Kebayoran Baru, Jakarta Selatan, DKI Jakarta',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '082137894516',
  },
  {
    name: 'Rizki Pratama',
    email: 'rizki.pratama33@gmail.com',
    username: 'rizki.prat',
    password: 'rizki2024@!',
    birth_date: new Date('1994-03-19'),
    gender: GENDER.Male,
    address: 'Jl. Thamrin no15, Thamrin, Jakarta Pusat, DKI Jakarta',
    city: 'Jakarta Pusat',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '085612349876',
  },
  {
    name: 'Ratna Sari',
    email: 'ratna.sari44@gmail.com',
    username: 'ratna.sar',
    password: 'ratna2024@!',
    birth_date: new Date('1993-04-14'),
    gender: GENDER.Female,
    address: 'Jl. Matraman no23, Matraman, Jakarta Timur, DKI Jakarta',
    city: 'Jakarta Timur',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '082134567892',
  },
  {
    name: 'Hendra Saputra',
    email: 'hendra.saputra99@gmail.com',
    username: 'hendra.sap',
    password: 'hendra2024@!',
    birth_date: new Date('1994-02-25'),
    gender: GENDER.Male,
    address: 'Jl. Merdeka no6, Merdeka, Jakarta Barat, DKI Jakarta',
    city: 'Jakarta Barat',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '081234678923',
  },
  {
    name: 'Mira Astari',
    email: 'mira.astari77@gmail.com',
    username: 'mira.ast',
    password: 'mira2024@!',
    birth_date: new Date('2001-05-16'),
    gender: GENDER.Female,
    address:
      'Jl. Kelapa Gading no18, Kelapa Gading, Jakarta Utara, DKI Jakarta',
    city: 'Jakarta Utara',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '082176543218',
  },
  {
    name: 'Fajar Rahman',
    email: 'fajar.rahman33@gmail.com',
    username: 'fajar.rah',
    password: 'fajar2024@!',
    birth_date: new Date('2000-06-13'),
    gender: GENDER.Male,
    address: 'Jl. Pluit no11, Pluit, Jakarta Utara, DKI Jakarta',
    city: 'Jakarta Utara',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '085673412389',
  },
  {
    name: 'Intan Permata',
    email: 'intan.permata88@gmail.com',
    username: 'intan.per',
    password: 'intan2024@!',
    birth_date: new Date('1996-05-25'),
    gender: GENDER.Female,
    address: 'Jl. Ancol Barat no2, Ancol, Jakarta Utara, DKI Jakarta',
    city: 'Jakarta Utara',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '082143567892',
  },
  {
    name: 'Teguh Purnomo',
    email: 'teguh.purnomo66@gmail.com',
    username: 'teguh.pur',
    password: 'teguh2024@!',
    birth_date: new Date('1990-04-24'),
    gender: GENDER.Male,
    address: 'Jl. Slipi Raya no9, Slipi, Jakarta Barat, DKI Jakarta',
    city: 'Jakarta Barat',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '081234598716',
  },
  {
    name: 'Wulan Sari',
    email: 'wulan.sari77@gmail.com',
    username: 'wulan.sar',
    password: 'wulan2024@!',
    birth_date: new Date('1998-12-05'),
    gender: GENDER.Female,
    address: 'Jl. Blok M no10, Blok M, Jakarta Selatan, DKI Jakarta',
    city: 'Jakarta Selatan',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '082145678932',
  },
  {
    name: 'Eko Prasetyo',
    email: 'eko.prasetyo99@gmail.com',
    username: 'eko.pras',
    password: 'eko2024@!',
    birth_date: new Date('1999-09-14'),
    gender: GENDER.Male,
    address: 'Jl. Rawamangun no14, Rawamangun, Jakarta Timur, DKI Jakarta',
    city: 'Jakarta Timur',
    province: 'DKI Jakarta',
    profile_desc: '',
    phone_number: '081234567890',
  },
];
